# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addemployee.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddEmployee(object):
    def setupUi(self, AddEmployee):
        AddEmployee.setObjectName("AddEmployee")
        AddEmployee.resize(400, 80)
        AddEmployee.setMinimumSize(QtCore.QSize(400, 80))
        AddEmployee.setMaximumSize(QtCore.QSize(400, 80))
        self.centralwidget = QtWidgets.QWidget(AddEmployee)
        self.centralwidget.setObjectName("centralwidget")
        self.employee_name_line = QtWidgets.QLineEdit(self.centralwidget)
        self.employee_name_line.setGeometry(QtCore.QRect(20, 20, 201, 21))
        self.employee_name_line.setObjectName("employee_name_line")
        self.position_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.position_combobox.setGeometry(QtCore.QRect(230, 20, 161, 22))
        self.position_combobox.setObjectName("position_combobox")
        self.add_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_button.setGeometry(QtCore.QRect(130, 50, 75, 23))
        self.add_button.setObjectName("add_button")
        self.cancel_button = QtWidgets.QPushButton(self.centralwidget)
        self.cancel_button.setGeometry(QtCore.QRect(220, 50, 75, 23))
        self.cancel_button.setObjectName("cancel_button")
        self.employee_name = QtWidgets.QLabel(self.centralwidget)
        self.employee_name.setGeometry(QtCore.QRect(80, 0, 81, 16))
        self.employee_name.setObjectName("employee_name")
        self.position_title = QtWidgets.QLabel(self.centralwidget)
        self.position_title.setGeometry(QtCore.QRect(290, 0, 47, 13))
        self.position_title.setObjectName("position_title")
        AddEmployee.setCentralWidget(self.centralwidget)

        self.retranslateUi(AddEmployee)
        QtCore.QMetaObject.connectSlotsByName(AddEmployee)

    def retranslateUi(self, AddEmployee):
        _translate = QtCore.QCoreApplication.translate
        AddEmployee.setWindowTitle(_translate("AddEmployee", "Add Employee"))
        self.add_button.setText(_translate("AddEmployee", "Add"))
        self.cancel_button.setText(_translate("AddEmployee", "Cancel"))
        self.employee_name.setText(_translate("AddEmployee", "Employee name"))
        self.position_title.setText(_translate("AddEmployee", "Position"))
