# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addschedule.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddSchedule(object):
    def setupUi(self, AddSchedule):
        AddSchedule.setObjectName("AddSchedule")
        AddSchedule.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(AddSchedule)
        self.centralwidget.setObjectName("centralwidget")
        AddSchedule.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AddSchedule)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        AddSchedule.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AddSchedule)
        self.statusbar.setObjectName("statusbar")
        AddSchedule.setStatusBar(self.statusbar)

        self.retranslateUi(AddSchedule)
        QtCore.QMetaObject.connectSlotsByName(AddSchedule)

    def retranslateUi(self, AddSchedule):
        _translate = QtCore.QCoreApplication.translate
        AddSchedule.setWindowTitle(_translate("AddSchedule", "MainWindow"))
