# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabBar = QtWidgets.QTabWidget(self.centralwidget)
        self.tabBar.setGeometry(QtCore.QRect(9, 9, 671, 581))
        self.tabBar.setObjectName("tabBar")
        self.employees = QtWidgets.QWidget()
        self.employees.setObjectName("employees")
        self.employeesTable = QtWidgets.QTableWidget(self.employees)
        self.employeesTable.setGeometry(QtCore.QRect(10, 10, 651, 541))
        self.employeesTable.setObjectName("employeesTable")
        self.employeesTable.setColumnCount(0)
        self.employeesTable.setRowCount(0)
        self.tabBar.addTab(self.employees, "")
        self.schedule = QtWidgets.QWidget()
        self.schedule.setObjectName("schedule")
        self.schedulesTable = QtWidgets.QTableWidget(self.schedule)
        self.schedulesTable.setGeometry(QtCore.QRect(10, 10, 651, 541))
        self.schedulesTable.setObjectName("schedulesTable")
        self.schedulesTable.setColumnCount(0)
        self.schedulesTable.setRowCount(0)
        self.tabBar.addTab(self.schedule, "")
        self.payments = QtWidgets.QWidget()
        self.payments.setObjectName("payments")
        self.paymentsTable = QtWidgets.QTableWidget(self.payments)
        self.paymentsTable.setGeometry(QtCore.QRect(10, 10, 651, 541))
        self.paymentsTable.setObjectName("paymentsTable")
        self.paymentsTable.setColumnCount(0)
        self.paymentsTable.setRowCount(0)
        self.tabBar.addTab(self.payments, "")
        self.positions = QtWidgets.QWidget()
        self.positions.setObjectName("positions")
        self.positionsTable = QtWidgets.QTableWidget(self.positions)
        self.positionsTable.setGeometry(QtCore.QRect(9, 9, 651, 541))
        self.positionsTable.setObjectName("positionsTable")
        self.positionsTable.setColumnCount(0)
        self.positionsTable.setRowCount(0)
        self.tabBar.addTab(self.positions, "")
        self.paymentStatus = QtWidgets.QWidget()
        self.paymentStatus.setObjectName("paymentStatus")
        self.payStatusTable = QtWidgets.QTableWidget(self.paymentStatus)
        self.payStatusTable.setGeometry(QtCore.QRect(10, 10, 651, 541))
        self.payStatusTable.setObjectName("payStatusTable")
        self.payStatusTable.setColumnCount(0)
        self.payStatusTable.setRowCount(0)
        self.tabBar.addTab(self.paymentStatus, "")
        self.addButton = QtWidgets.QPushButton(self.centralwidget)
        self.addButton.setGeometry(QtCore.QRect(690, 40, 91, 23))
        self.addButton.setObjectName("addButton")
        self.editButton = QtWidgets.QPushButton(self.centralwidget)
        self.editButton.setGeometry(QtCore.QRect(690, 80, 91, 23))
        self.editButton.setObjectName("editButton")
        self.delButton = QtWidgets.QPushButton(self.centralwidget)
        self.delButton.setGeometry(QtCore.QRect(690, 120, 91, 23))
        self.delButton.setObjectName("delButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabBar.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Salary calculation"))
        self.tabBar.setTabText(self.tabBar.indexOf(self.employees), _translate("MainWindow", "Employees"))
        self.tabBar.setTabText(self.tabBar.indexOf(self.schedule), _translate("MainWindow", "Schedule"))
        self.tabBar.setTabText(self.tabBar.indexOf(self.payments), _translate("MainWindow", "Payments"))
        self.tabBar.setTabText(self.tabBar.indexOf(self.positions), _translate("MainWindow", "Positions"))
        self.tabBar.setTabText(self.tabBar.indexOf(self.paymentStatus), _translate("MainWindow", "Pay status"))
        self.addButton.setText(_translate("MainWindow", "Add"))
        self.editButton.setText(_translate("MainWindow", "Edit"))
        self.delButton.setText(_translate("MainWindow", "Delete"))
